### ISSUE TITLE
Pokemon team planner 404 unresponsive

### ISSUE THREAD

**Issue by jlankau** [richi3f/pokemon-team-planner#4]
Getting a 404 error for the national dex

**Comment by richi3f** [comment]
Hello, the team planner is undergoing changes to support the upcoming mainline games, so some features are being temporarily being disabled and some links may be dead. As of #5, the national dex has been re-implemented (shown in the game picker as [Pokémon HOME](https://richi3f.github.io/pokemon-team-planner/plan/#home)). However, you're right that the previous URL displays a 404 error, which I will address with a redirect.

**Comment by Gordy12** [comment]
Will the old version of the team planner be available in some form? I appreciate all the hard work you put into the newer versions, but I personally like using the versions with the official stock art, smaller icons and the older, simpler type layouts.

**Comment by richi3f** [comment]
@Gordy12 Unfortunately, I will not continue giving support to the older versions.

There are several reasons to use the art from Pokémon HOME instead of the old smaller icons, namely:

- the sprite formats differ between game versions (e.g., sprites in LGPE are different than sprites in SWSH, BDSP introduces totally new sprites),
- no single game has sprites for every Pokémon (e.g., BDSP only has sprites for the first 493 Pokémon),

Although I might bring back the official art at some point. For now, it is easier to work with the renders from Pokémon HOME.

If you want to access the previous planners for personal use, you might want to clone the current repositories and roll them back to a previous commit.
