### ISSUE TITLE
Colo/XD?

### ISSUE THREAD

**Issue by starwolf27** [richi3f/pokemon-team-planner#58]
Love your thing! But you should add Colosseum and XD Gale of Darkness as games.

**Comment by A-b-e-l** [comment]
"A non-competitive team planner tool for **mainline** Pokémon games."

**Comment by sleepiemeepie** [comment]
> "A non-competitive team planner tool for **mainline** Pokémon games."

I don't see why this shouldn't include Colosseum / XD. They're games with a story where you can build a team of Pokemon, why not? I think a tool like this could be really nice to have.

**Comment by richi3f** [comment]
@Meeper12346 I would gladly include them, but currently I have very limited time that I can devote to this project. If you or anyone else were to compile an itemized list of Pokémon available in those games, then it would make the work much easier.

**Comment by sleepiemeepie** [comment]
@richi3f Completely understand! I can jot down a list to help out with the process :)

### **Colosseum Pokémon**
(asterisk (*) = postgame story capture, unsure if you'd display these seperately since it depends if you define colosseum's end as after the final boss or after snagging every shadow pokemon, but it's probably worth including anyways since zacian/zamazenta are included on swsh's team planner)
(**_e_** = exclusive to the Japan-only _e-Reader_ - togepi and mareep are in this camp, but their evolutions are not)

Bayleef
Meganium
Quilava
Typhlosion
Croconaw
Feraligatr
Furret
Noctowl
Ledian
Ariados
Togepi **_e_**
Togetic*
Mareep **_e_**
Flaaffy
Ampharos
Sudowoodo
Skiploom
Jumpluff
Aipom
Sunflora
Yanma
Quagsire
Espeon
Umbreon
Murkrow
Misdreavus
Forretress
Dunsparce
Gligar
Granbull
Qwilfish
Scizor **_e_**
Shuckle*
Heracross
Sneasel
Ursaring*
Slugma
Magcargo
Piloswine
Remoraid
Octillery
Delibird
Mantine
Skarmory
Houndoom
Stantler
Smeargle*
Hitmontop
Miltank
Raikou
Entei
Suicune
Ho-Oh*
Tyranitar
Makuhita
Hariyama
Meditite
Medicham
Plusle
Vibrava
Flygon
Swablu
Altaria
Tropius
Absol
Metagross

### **XD Pokémon**
(asterisk (*) = postgame story capture)

Butterfree
Beedrill
Pidgeotto
Pidgeot
Raticate
Spearow
Fearow
Arbok
Sandshrew
Sandslash
Vulpix
Ninetales
Zubat
Golbat
Crobat
Paras
Parasect
Venomoth
Dugtrio
Meowth
Persian
Golduck
Primeape
Growlithe
Arcanine
Poliwrath
Weepinbell
Victreebel
Rapidash
Magneton
Farfetch'd
Dodrio
Seel
Dewgong
Grimer
Muk
Shellder
Cloyster
Hypno
Voltorb
Electrode
Exeggutor
Marowak
Hitmonlee
Hitmonchan
Lickitung
Rhydon
Chansey
Blissey
Tangela
Kangaskhan
Starmie
Mr. Mime
Scyther
Elekid
Electabuzz
Magmar
Pinsir
Tauros
Lapras
Eevee
Vaporeon
Jolteon
Flareon
Espeon
Umbreon
Snorlax
Articuno
Zapdos
Moltres
Dragonite*
Chikorita
Bayleef
Meganium
Cyndaquil
Quilava
Typhlosion
Totodile
Croconaw
Feraligatr
Ledyba
Ledian
Spinarak
Ariados
Togepi
Togetic
Natu
Xatu
Mareep
Flaaffy
Ampharos
Hoppip
Skiploom
Jumpluff
Wooper
Quagsire
Pineco
Forretress
Gligar
Shuckle
Teddiursa
Ursaring
Magcargo
Swinub
Piloswine
Houndour
Houndoom
Phanpy
Donphan
Larvitar
Pupitar
Tyranitar
Lugia (**XD001**)
Poochyena
Mightyena
Seedot
Nuzleaf
Shiftry
Swellow
Ralts
Kirlia
Gardevoir
Surskit
Masquerain
Shroomish
Breloom
Makuhita
Hariyama
Nosepass
Delcatty
Sableye
Mawile
Aron
Lairon
Aggron
Meditite
Medicham
Manectric
Roselia
Gulpin
Swalot
Carvanha
Sharpedo
Numel
Camerupt
Trapinch
Vibrava
Flygon
Altaria
Zangoose
Lunatone
Solrock
Baltoy
Claydol
Banette
Duskull
Dusclops
Snorunt
Glalie
Spheal
Sealeo
Walrein
Salamence

This should hopefully be all of them - I hope it's helpful! Thank you for creating such a useful website. One minor detail is that Orre also doesn't have a traditional Pokédex, so technically the header could read "[Snag List](https://bulbapedia.bulbagarden.net/wiki/File:PDA_Menu.png)" instead of "Orre Pokédex", though that might be a misnomer since not every Pokemon obtainable is snaggable (quite a few are simply given to the player)
