### ISSUE TITLE
Did someone use your code?

### ISSUE THREAD

**Issue by rpfontana** [richi3f/pokemon-team-planner#63]
Hi, I don't if you are aware of this but there's a site that literally use a copy-paste of your code inside of his project. Since the goal of the site is the same as your, I don't think that's correct.

Probably you're already aware of this, but I just want to warn you since your site is amazing (and you were the first one).

The site is [this](https://pokemonteambuilder.net/)

**Comment by richi3f** [comment]
Hello, thanks for the message! I was already aware of this website. You're right: they have taken my code without any permission (hopefully not for profit), which is a shame because they don't update/ensure it works properly and I have had users messaging about bugs in that site. Unfortunately, I do not know who to address this for it to be taken down.

**Comment by nchpmn** [comment]
Not that it's necessarily accurate, but the whois for the domain name returns:

> **Registrant Contact Information:**
> Name: hemant dudeja
> Organization: hemant dudeja
> Address: vpo chang
> City: bhiwani
> State / Province: haryana
> Postal Code: 127027
> Country: IN
> Phone: +91.9716001047
> Email: mathdeft1@gmail.com

The city, state and postcode are all accurate to each other, and +91 is India's country code - so perhaps the email address will get you to the correct person?

(btw, thanks for the tool!)
